### ISSUE TITLE
appeared constantly re-open re-close of electron login window after I using google contact logined

### ISSUE THREAD

**Issue by weykon** [diciaup/assistant-cli#1]
as title
![Dec-12-2022 09-43-03](https://user-images.githubusercontent.com/36456814/206953460-89f3b485-2fc0-4ca1-9aee-5ec254215bf3.gif)
it is running automatically

**Comment by weykon** [comment]
it is v16.17.0

**Comment by weykon** [comment]
and I using Stage Management in Ventura. probably

**Comment by diciaup** [comment]
I pushed an hotfix, you can find it in the 1.1.5 version, today the open ai changed cookies handling, i introduced the new cookie cf_clearance handling. You have to clear session with command: 'assistant reset auth' before retry

**Comment by weykon** [comment]
my version is 1.1.5 now, and I run 'assistant reset auth'

but still, the problem occurs

**Comment by diciaup** [comment]
Sorry there was some problems that i fixed after the implementation of Cloudflare by OpenAI. 
With the version 1.2.1 you shouldn't have any problem, i tested with Ventura and Ubuntu (WSL).

You can launch 'assistant clean' to reset session

**Comment by weykon** [comment]
I updated to version 1.2.3, the problem was gone !

**Comment by likakuli** [comment]
same problem with 1.4.0 macos
