### ISSUE TITLE
Context don't persist in "assistant chat"

### ISSUE THREAD

**Issue by MystWalkerOfficial** [diciaup/assistant-cli#6]
**Describe the bug**
Idk if it's my setup, windows (version), but whenever i say "could you expand more?" Chatgpt replies as if it's a new conversation and asks for context. I've installed it just like the instruction said "npm install -g assistant-cli". I haven't tried this on linux but seeing the screenshot in the README.md i assume it works fine there.

**AssistantCli Version**
1.3.6

**To Reproduce**
1. Launch command 'assistant chat'
2. Start a conversation that requires future contexts
3. Ask it a task that requires context of the last conversation

**Expected behavior**
It should know what the context of the last conversation

**Screenshots**
![image_2023-01-19_173930667](https://user-images.githubusercontent.com/58080207/213599650-b0fda3bc-d160-4c93-97f3-a3ab6564e969.png)

**CLI (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - AssistantCli Version: 1.3.6

**Comment by diciaup** [comment]
Thanks, you can find the fix on version 1.4.0, the continuous conversation is also available with standard mode, so if you write two different commands it will keep the same context. In the next releases, i will create a command to switch conversation from CLI
